<pre class='metadata'>
Title: media-fill Tag
Work Status: Testing
Shortname: media-fill
Level: 1
Group: Number 3
Abstract: This module introduces HTML element that designed to display animated text filled with media content, such as videos or pictures, on web pages.
</pre>

<pre class=link-defaults>
spec:css-values-4; type:dfn; text:identifier
spec:css-color-4; type:property; text:color
spec:selectors-4; type:selector; text: :lang()
</pre>

